### PR TITLE
Fix SSR and portals in Svelte Flow & update Astro Example

### LINKED ISSUE #5330: Pressing Spacebar in an input on a custom node selects the first edge
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Live code example

_No response_

### Describe the Bug

Pressing Spacebar in an input on a custom node selects the first edge

### Steps to reproduce the bug or issue

***

### Expected behavior

***

### Screenshots or Videos

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peterkogo**
fixes #5330

### CODE REVIEW

File: packages/svelte/src/lib/components/ViewportPortal/ViewportPortal.svelte [hunk 1]
```diff
@@ -1,10 +1,10 @@
 <script lang="ts">
-  import { portal } from '$lib/actions/portal';
+  import { hideDuringSSR, portal } from '$lib/actions/portal';
   import type { ViewportPortalProps } from './types';
 
   let { target = 'front', children, ...rest }: ViewportPortalProps = $props();
 </script>
 
-<div use:portal={`viewport-${target}`} {...rest}>
+<div use:portal={`viewport-${target}`} style:display={hideDuringSSR().display} {...rest}>
```
Comment (moklick) [inline packages/svelte/src/lib/components/ViewportPortal/ViewportPortal.svelte]: the naming here is a bit confusing to me:

`style:display={hideDuringSSR().display`

is this hidden during SSR? why is there a `display` field?

Comment (peterkogo) [reply packages/svelte/src/lib/components/ViewportPortal/ViewportPortal.svelte]: Yeah let me see if I can improve this. It's because `.display` needs to be reactive

Comment (peterkogo) [reply packages/svelte/src/lib/components/ViewportPortal/ViewportPortal.svelte]: and it outputs the value for display ('none' | undefined)

**Comment by moklick** [comment]
huge!
